config:
  default: true
  MD013: false # Disable line length check
  MD025: false # Allow title in frontmatter and H1 in body
  MD033:
    allowed_elements:
      - img

globs:
  - "docs/**/*.md"
  - "README.md"